namespace EF_Practice.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ComponentDBv2 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.ManufacturerGPUs", "Manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.ManufacturerGPUs", "GPU_id", "dbo.GPUs");
            DropForeignKey("dbo.GPUs", "gpu_interface_id", "dbo.Component_interface");
            DropForeignKey("dbo.ROMs", "_interface_id", "dbo.Component_interface");
            DropForeignKey("dbo.GPUs", "GPU_frame_Sync_id", "dbo.GPU_frame_sync");
            DropForeignKey("dbo.GPUs", "GPU_technology_id", "dbo.GPU_technology");
            DropForeignKey("dbo.GPUs", "ram_type_id", "dbo.RAM_type");
            DropForeignKey("dbo.CPU_Cooler", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.CPUs", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.Motherboards", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.PS", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.RAMs", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.ROMs", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.CPUs", "socket_id", "dbo.CPU_Socket");
            DropForeignKey("dbo.CPUs", "microarchitecture_id", "dbo.CPU_Microarchitecture");
            DropForeignKey("dbo.CPUs", "series_id", "dbo.CPU_Serie");
            DropForeignKey("dbo.Motherboards", "motherboard_chipset_id", "dbo.Motherboard_chipset");
            DropForeignKey("dbo.Motherboards", "motherboard_form_factor_id", "dbo.Motherboard_form_factor");
            DropForeignKey("dbo.Motherboards", "RAM_Type_id", "dbo.RAM_type");
            DropForeignKey("dbo.Motherboards", "socket_id", "dbo.CPU_Socket");
            DropForeignKey("dbo.M2", "form_id", "dbo.M2_form_factor");
            DropForeignKey("dbo.RAMs", "RAM_Type_id", "dbo.RAM_type");
            DropForeignKey("dbo.PS", "form_id", "dbo.PS_form_factor");
            DropForeignKey("dbo.PS", "rating_id", "dbo.PS_Rating");
            DropForeignKey("dbo.ROMs", "form_Factor_id", "dbo.ROM_form_factor");
            DropForeignKey("dbo.ROMs", "type_id", "dbo.ROM_Type");
            DropIndex("dbo.GPUs", new[] { "GPU_frame_Sync_id" });
            DropIndex("dbo.GPUs", new[] { "gpu_interface_id" });
            DropIndex("dbo.GPUs", new[] { "GPU_technology_id" });
            DropIndex("dbo.GPUs", new[] { "ram_type_id" });
            DropIndex("dbo.CPU_Cooler", new[] { "manufacturer_id" });
            DropIndex("dbo.CPUs", new[] { "manufacturer_id" });
            DropIndex("dbo.CPUs", new[] { "microarchitecture_id" });
            DropIndex("dbo.CPUs", new[] { "series_id" });
            DropIndex("dbo.CPUs", new[] { "socket_id" });
            DropIndex("dbo.Motherboards", new[] { "manufacturer_id" });
            DropIndex("dbo.Motherboards", new[] { "motherboard_chipset_id" });
            DropIndex("dbo.Motherboards", new[] { "motherboard_form_factor_id" });
            DropIndex("dbo.Motherboards", new[] { "RAM_Type_id" });
            DropIndex("dbo.Motherboards", new[] { "socket_id" });
            DropIndex("dbo.M2", new[] { "form_id" });
            DropIndex("dbo.RAMs", new[] { "manufacturer_id" });
            DropIndex("dbo.RAMs", new[] { "RAM_Type_id" });
            DropIndex("dbo.PS", new[] { "form_id" });
            DropIndex("dbo.PS", new[] { "manufacturer_id" });
            DropIndex("dbo.PS", new[] { "rating_id" });
            DropIndex("dbo.ROMs", new[] { "_interface_id" });
            DropIndex("dbo.ROMs", new[] { "form_Factor_id" });
            DropIndex("dbo.ROMs", new[] { "manufacturer_id" });
            DropIndex("dbo.ROMs", new[] { "type_id" });
            DropIndex("dbo.ManufacturerGPUs", new[] { "Manufacturer_id" });
            DropIndex("dbo.ManufacturerGPUs", new[] { "GPU_id" });
            RenameColumn(table: "dbo.Motherboards", name: "id", newName: "MotherboardID");
            AddColumn("dbo.GPUs", "additional_info", c => c.String(maxLength: 20));
            AddColumn("dbo.GPUs", "manufacturer_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Component_interface", "interface_type", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.GPUs", "model", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.GPUs", "brand", c => c.String(maxLength: 25));
            AlterColumn("dbo.GPUs", "hdmi_output", c => c.Int());
            AlterColumn("dbo.GPUs", "dp_port_output", c => c.Int());
            AlterColumn("dbo.GPUs", "GPU_frame_Sync_id", c => c.Int(nullable: false));
            AlterColumn("dbo.GPUs", "gpu_interface_id", c => c.Int(nullable: false));
            AlterColumn("dbo.GPUs", "GPU_technology_id", c => c.Int(nullable: false));
            AlterColumn("dbo.GPUs", "ram_type_id", c => c.Int(nullable: false));
            AlterColumn("dbo.GPU_frame_sync", "sync", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.GPU_technology", "technology", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.Manufacturers", "name", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.CPU_Cooler", "model", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.CPU_Cooler", "manufacturer_id", c => c.Int(nullable: false));
            AlterColumn("dbo.CPU_Socket", "type", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.CPUs", "model", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.CPUs", "manufacturer_id", c => c.Int(nullable: false));
            AlterColumn("dbo.CPUs", "microarchitecture_id", c => c.Int(nullable: false));
            AlterColumn("dbo.CPUs", "series_id", c => c.Int(nullable: false));
            AlterColumn("dbo.CPUs", "socket_id", c => c.Int(nullable: false));
            AlterColumn("dbo.CPU_Microarchitecture", "architecture", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.CPU_Serie", "serie", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Motherboards", "model", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Motherboards", "manufacturer_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Motherboards", "motherboard_chipset_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Motherboards", "motherboard_form_factor_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Motherboards", "RAM_Type_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Motherboards", "socket_id", c => c.Int(nullable: false));
            AlterColumn("dbo.M2", "form_id", c => c.Int(nullable: false));
            AlterColumn("dbo.M2_form_factor", "form", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.Motherboard_chipset", "chipset", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.Motherboard_form_factor", "form", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.RAM_type", "ram_type", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.RAMs", "model", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.RAMs", "manufacturer_id", c => c.Int(nullable: false));
            AlterColumn("dbo.RAMs", "RAM_Type_id", c => c.Int(nullable: false));
            AlterColumn("dbo.PS", "model", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.PS", "form_id", c => c.Int(nullable: false));
            AlterColumn("dbo.PS", "manufacturer_id", c => c.Int(nullable: false));
            AlterColumn("dbo.PS", "rating_id", c => c.Int(nullable: false));
            AlterColumn("dbo.PS_form_factor", "form", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.PS_Rating", "rating", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.ROMs", "model", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.ROMs", "_interface_id", c => c.Int(nullable: false));
            AlterColumn("dbo.ROMs", "form_Factor_id", c => c.Int(nullable: false));
            AlterColumn("dbo.ROMs", "manufacturer_id", c => c.Int(nullable: false));
            AlterColumn("dbo.ROMs", "type_id", c => c.Int(nullable: false));
            AlterColumn("dbo.ROM_form_factor", "form_factor", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.ROM_Type", "type", c => c.String(nullable: false, maxLength: 5));
            CreateIndex("dbo.GPUs", "GPU_frame_Sync_id");
            CreateIndex("dbo.GPUs", "gpu_interface_id");
            CreateIndex("dbo.GPUs", "GPU_technology_id");
            CreateIndex("dbo.GPUs", "manufacturer_id");
            CreateIndex("dbo.GPUs", "ram_type_id");
            CreateIndex("dbo.CPU_Cooler", "manufacturer_id");
            CreateIndex("dbo.CPUs", "manufacturer_id");
            CreateIndex("dbo.CPUs", "microarchitecture_id");
            CreateIndex("dbo.CPUs", "series_id");
            CreateIndex("dbo.CPUs", "socket_id");
            CreateIndex("dbo.Motherboards", "manufacturer_id");
            CreateIndex("dbo.Motherboards", "motherboard_chipset_id");
            CreateIndex("dbo.Motherboards", "motherboard_form_factor_id");
            CreateIndex("dbo.Motherboards", "RAM_Type_id");
            CreateIndex("dbo.Motherboards", "socket_id");
            CreateIndex("dbo.M2", "form_id");
            CreateIndex("dbo.RAMs", "manufacturer_id");
            CreateIndex("dbo.RAMs", "RAM_Type_id");
            CreateIndex("dbo.PS", "form_id");
            CreateIndex("dbo.PS", "manufacturer_id");
            CreateIndex("dbo.PS", "rating_id");
            CreateIndex("dbo.ROMs", "_interface_id");
            CreateIndex("dbo.ROMs", "form_Factor_id");
            CreateIndex("dbo.ROMs", "manufacturer_id");
            CreateIndex("dbo.ROMs", "type_id");
            AddForeignKey("dbo.GPUs", "manufacturer_id", "dbo.Manufacturers", "id", cascadeDelete: true);
            AddForeignKey("dbo.GPUs", "gpu_interface_id", "dbo.Component_interface", "id", cascadeDelete: true);
            AddForeignKey("dbo.ROMs", "_interface_id", "dbo.Component_interface", "id", cascadeDelete: true);
            AddForeignKey("dbo.GPUs", "GPU_frame_Sync_id", "dbo.GPU_frame_sync", "id", cascadeDelete: true);
            AddForeignKey("dbo.GPUs", "GPU_technology_id", "dbo.GPU_technology", "id", cascadeDelete: true);
            AddForeignKey("dbo.GPUs", "ram_type_id", "dbo.RAM_type", "id", cascadeDelete: true);
            AddForeignKey("dbo.CPU_Cooler", "manufacturer_id", "dbo.Manufacturers", "id", cascadeDelete: true);
            AddForeignKey("dbo.CPUs", "manufacturer_id", "dbo.Manufacturers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Motherboards", "manufacturer_id", "dbo.Manufacturers", "id", cascadeDelete: true);
            AddForeignKey("dbo.PS", "manufacturer_id", "dbo.Manufacturers", "id", cascadeDelete: true);
            AddForeignKey("dbo.RAMs", "manufacturer_id", "dbo.Manufacturers", "id", cascadeDelete: true);
            AddForeignKey("dbo.ROMs", "manufacturer_id", "dbo.Manufacturers", "id", cascadeDelete: true);
            AddForeignKey("dbo.CPUs", "socket_id", "dbo.CPU_Socket", "id", cascadeDelete: true);
            AddForeignKey("dbo.CPUs", "microarchitecture_id", "dbo.CPU_Microarchitecture", "id", cascadeDelete: true);
            AddForeignKey("dbo.CPUs", "series_id", "dbo.CPU_Serie", "id", cascadeDelete: true);
            AddForeignKey("dbo.Motherboards", "motherboard_chipset_id", "dbo.Motherboard_chipset", "id", cascadeDelete: true);
            AddForeignKey("dbo.Motherboards", "motherboard_form_factor_id", "dbo.Motherboard_form_factor", "id", cascadeDelete: true);
            AddForeignKey("dbo.Motherboards", "RAM_Type_id", "dbo.RAM_type", "id", cascadeDelete: true);
            AddForeignKey("dbo.Motherboards", "socket_id", "dbo.CPU_Socket", "id", cascadeDelete: true);
            AddForeignKey("dbo.M2", "form_id", "dbo.M2_form_factor", "id", cascadeDelete: true);
            AddForeignKey("dbo.RAMs", "RAM_Type_id", "dbo.RAM_type", "id", cascadeDelete: true);
            AddForeignKey("dbo.PS", "form_id", "dbo.PS_form_factor", "id", cascadeDelete: true);
            AddForeignKey("dbo.PS", "rating_id", "dbo.PS_Rating", "id", cascadeDelete: true);
            AddForeignKey("dbo.ROMs", "form_Factor_id", "dbo.ROM_form_factor", "id", cascadeDelete: true);
            AddForeignKey("dbo.ROMs", "type_id", "dbo.ROM_Type", "id", cascadeDelete: true);
            DropTable("dbo.ManufacturerGPUs");
        }
        
        public override void Down()
        {
            CreateTable(
                "dbo.ManufacturerGPUs",
                c => new
                    {
                        Manufacturer_id = c.Int(nullable: false),
                        GPU_id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.Manufacturer_id, t.GPU_id });
            
            DropForeignKey("dbo.ROMs", "type_id", "dbo.ROM_Type");
            DropForeignKey("dbo.ROMs", "form_Factor_id", "dbo.ROM_form_factor");
            DropForeignKey("dbo.PS", "rating_id", "dbo.PS_Rating");
            DropForeignKey("dbo.PS", "form_id", "dbo.PS_form_factor");
            DropForeignKey("dbo.RAMs", "RAM_Type_id", "dbo.RAM_type");
            DropForeignKey("dbo.M2", "form_id", "dbo.M2_form_factor");
            DropForeignKey("dbo.Motherboards", "socket_id", "dbo.CPU_Socket");
            DropForeignKey("dbo.Motherboards", "RAM_Type_id", "dbo.RAM_type");
            DropForeignKey("dbo.Motherboards", "motherboard_form_factor_id", "dbo.Motherboard_form_factor");
            DropForeignKey("dbo.Motherboards", "motherboard_chipset_id", "dbo.Motherboard_chipset");
            DropForeignKey("dbo.CPUs", "series_id", "dbo.CPU_Serie");
            DropForeignKey("dbo.CPUs", "microarchitecture_id", "dbo.CPU_Microarchitecture");
            DropForeignKey("dbo.CPUs", "socket_id", "dbo.CPU_Socket");
            DropForeignKey("dbo.ROMs", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.RAMs", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.PS", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.Motherboards", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.CPUs", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.CPU_Cooler", "manufacturer_id", "dbo.Manufacturers");
            DropForeignKey("dbo.GPUs", "ram_type_id", "dbo.RAM_type");
            DropForeignKey("dbo.GPUs", "GPU_technology_id", "dbo.GPU_technology");
            DropForeignKey("dbo.GPUs", "GPU_frame_Sync_id", "dbo.GPU_frame_sync");
            DropForeignKey("dbo.ROMs", "_interface_id", "dbo.Component_interface");
            DropForeignKey("dbo.GPUs", "gpu_interface_id", "dbo.Component_interface");
            DropForeignKey("dbo.GPUs", "manufacturer_id", "dbo.Manufacturers");
            DropIndex("dbo.ROMs", new[] { "type_id" });
            DropIndex("dbo.ROMs", new[] { "manufacturer_id" });
            DropIndex("dbo.ROMs", new[] { "form_Factor_id" });
            DropIndex("dbo.ROMs", new[] { "_interface_id" });
            DropIndex("dbo.PS", new[] { "rating_id" });
            DropIndex("dbo.PS", new[] { "manufacturer_id" });
            DropIndex("dbo.PS", new[] { "form_id" });
            DropIndex("dbo.RAMs", new[] { "RAM_Type_id" });
            DropIndex("dbo.RAMs", new[] { "manufacturer_id" });
            DropIndex("dbo.M2", new[] { "form_id" });
            DropIndex("dbo.Motherboards", new[] { "socket_id" });
            DropIndex("dbo.Motherboards", new[] { "RAM_Type_id" });
            DropIndex("dbo.Motherboards", new[] { "motherboard_form_factor_id" });
            DropIndex("dbo.Motherboards", new[] { "motherboard_chipset_id" });
            DropIndex("dbo.Motherboards", new[] { "manufacturer_id" });
            DropIndex("dbo.CPUs", new[] { "socket_id" });
            DropIndex("dbo.CPUs", new[] { "series_id" });
            DropIndex("dbo.CPUs", new[] { "microarchitecture_id" });
            DropIndex("dbo.CPUs", new[] { "manufacturer_id" });
            DropIndex("dbo.CPU_Cooler", new[] { "manufacturer_id" });
            DropIndex("dbo.GPUs", new[] { "ram_type_id" });
            DropIndex("dbo.GPUs", new[] { "manufacturer_id" });
            DropIndex("dbo.GPUs", new[] { "GPU_technology_id" });
            DropIndex("dbo.GPUs", new[] { "gpu_interface_id" });
            DropIndex("dbo.GPUs", new[] { "GPU_frame_Sync_id" });
            AlterColumn("dbo.ROM_Type", "type", c => c.String());
            AlterColumn("dbo.ROM_form_factor", "form_factor", c => c.String());
            AlterColumn("dbo.ROMs", "type_id", c => c.Int());
            AlterColumn("dbo.ROMs", "manufacturer_id", c => c.Int());
            AlterColumn("dbo.ROMs", "form_Factor_id", c => c.Int());
            AlterColumn("dbo.ROMs", "_interface_id", c => c.Int());
            AlterColumn("dbo.ROMs", "model", c => c.String());
            AlterColumn("dbo.PS_Rating", "rating", c => c.String());
            AlterColumn("dbo.PS_form_factor", "form", c => c.String());
            AlterColumn("dbo.PS", "rating_id", c => c.Int());
            AlterColumn("dbo.PS", "manufacturer_id", c => c.Int());
            AlterColumn("dbo.PS", "form_id", c => c.Int());
            AlterColumn("dbo.PS", "model", c => c.String());
            AlterColumn("dbo.RAMs", "RAM_Type_id", c => c.Int());
            AlterColumn("dbo.RAMs", "manufacturer_id", c => c.Int());
            AlterColumn("dbo.RAMs", "model", c => c.String());
            AlterColumn("dbo.RAM_type", "ram_type", c => c.String());
            AlterColumn("dbo.Motherboard_form_factor", "form", c => c.String());
            AlterColumn("dbo.Motherboard_chipset", "chipset", c => c.String());
            AlterColumn("dbo.M2_form_factor", "form", c => c.String());
            AlterColumn("dbo.M2", "form_id", c => c.Int());
            AlterColumn("dbo.Motherboards", "socket_id", c => c.Int());
            AlterColumn("dbo.Motherboards", "RAM_Type_id", c => c.Int());
            AlterColumn("dbo.Motherboards", "motherboard_form_factor_id", c => c.Int());
            AlterColumn("dbo.Motherboards", "motherboard_chipset_id", c => c.Int());
            AlterColumn("dbo.Motherboards", "manufacturer_id", c => c.Int());
            AlterColumn("dbo.Motherboards", "model", c => c.String());
            AlterColumn("dbo.CPU_Serie", "serie", c => c.String());
            AlterColumn("dbo.CPU_Microarchitecture", "architecture", c => c.String());
            AlterColumn("dbo.CPUs", "socket_id", c => c.Int());
            AlterColumn("dbo.CPUs", "series_id", c => c.Int());
            AlterColumn("dbo.CPUs", "microarchitecture_id", c => c.Int());
            AlterColumn("dbo.CPUs", "manufacturer_id", c => c.Int());
            AlterColumn("dbo.CPUs", "model", c => c.String());
            AlterColumn("dbo.CPU_Socket", "type", c => c.String());
            AlterColumn("dbo.CPU_Cooler", "manufacturer_id", c => c.Int());
            AlterColumn("dbo.CPU_Cooler", "model", c => c.String());
            AlterColumn("dbo.Manufacturers", "name", c => c.String());
            AlterColumn("dbo.GPU_technology", "technology", c => c.String());
            AlterColumn("dbo.GPU_frame_sync", "sync", c => c.String());
            AlterColumn("dbo.GPUs", "ram_type_id", c => c.Int());
            AlterColumn("dbo.GPUs", "GPU_technology_id", c => c.Int());
            AlterColumn("dbo.GPUs", "gpu_interface_id", c => c.Int());
            AlterColumn("dbo.GPUs", "GPU_frame_Sync_id", c => c.Int());
            AlterColumn("dbo.GPUs", "dp_port_output", c => c.Int(nullable: false));
            AlterColumn("dbo.GPUs", "hdmi_output", c => c.Int(nullable: false));
            AlterColumn("dbo.GPUs", "brand", c => c.String());
            AlterColumn("dbo.GPUs", "model", c => c.String());
            AlterColumn("dbo.Component_interface", "interface_type", c => c.String());
            DropColumn("dbo.GPUs", "manufacturer_id");
            DropColumn("dbo.GPUs", "additional_info");
            RenameColumn(table: "dbo.Motherboards", name: "MotherboardID", newName: "id");
            CreateIndex("dbo.ManufacturerGPUs", "GPU_id");
            CreateIndex("dbo.ManufacturerGPUs", "Manufacturer_id");
            CreateIndex("dbo.ROMs", "type_id");
            CreateIndex("dbo.ROMs", "manufacturer_id");
            CreateIndex("dbo.ROMs", "form_Factor_id");
            CreateIndex("dbo.ROMs", "_interface_id");
            CreateIndex("dbo.PS", "rating_id");
            CreateIndex("dbo.PS", "manufacturer_id");
            CreateIndex("dbo.PS", "form_id");
            CreateIndex("dbo.RAMs", "RAM_Type_id");
            CreateIndex("dbo.RAMs", "manufacturer_id");
            CreateIndex("dbo.M2", "form_id");
            CreateIndex("dbo.Motherboards", "socket_id");
            CreateIndex("dbo.Motherboards", "RAM_Type_id");
            CreateIndex("dbo.Motherboards", "motherboard_form_factor_id");
            CreateIndex("dbo.Motherboards", "motherboard_chipset_id");
            CreateIndex("dbo.Motherboards", "manufacturer_id");
            CreateIndex("dbo.CPUs", "socket_id");
            CreateIndex("dbo.CPUs", "series_id");
            CreateIndex("dbo.CPUs", "microarchitecture_id");
            CreateIndex("dbo.CPUs", "manufacturer_id");
            CreateIndex("dbo.CPU_Cooler", "manufacturer_id");
            CreateIndex("dbo.GPUs", "ram_type_id");
            CreateIndex("dbo.GPUs", "GPU_technology_id");
            CreateIndex("dbo.GPUs", "gpu_interface_id");
            CreateIndex("dbo.GPUs", "GPU_frame_Sync_id");
            AddForeignKey("dbo.ROMs", "type_id", "dbo.ROM_Type", "id");
            AddForeignKey("dbo.ROMs", "form_Factor_id", "dbo.ROM_form_factor", "id");
            AddForeignKey("dbo.PS", "rating_id", "dbo.PS_Rating", "id");
            AddForeignKey("dbo.PS", "form_id", "dbo.PS_form_factor", "id");
            AddForeignKey("dbo.RAMs", "RAM_Type_id", "dbo.RAM_type", "id");
            AddForeignKey("dbo.M2", "form_id", "dbo.M2_form_factor", "id");
            AddForeignKey("dbo.Motherboards", "socket_id", "dbo.CPU_Socket", "id");
            AddForeignKey("dbo.Motherboards", "RAM_Type_id", "dbo.RAM_type", "id");
            AddForeignKey("dbo.Motherboards", "motherboard_form_factor_id", "dbo.Motherboard_form_factor", "id");
            AddForeignKey("dbo.Motherboards", "motherboard_chipset_id", "dbo.Motherboard_chipset", "id");
            AddForeignKey("dbo.CPUs", "series_id", "dbo.CPU_Serie", "id");
            AddForeignKey("dbo.CPUs", "microarchitecture_id", "dbo.CPU_Microarchitecture", "id");
            AddForeignKey("dbo.CPUs", "socket_id", "dbo.CPU_Socket", "id");
            AddForeignKey("dbo.ROMs", "manufacturer_id", "dbo.Manufacturers", "id");
            AddForeignKey("dbo.RAMs", "manufacturer_id", "dbo.Manufacturers", "id");
            AddForeignKey("dbo.PS", "manufacturer_id", "dbo.Manufacturers", "id");
            AddForeignKey("dbo.Motherboards", "manufacturer_id", "dbo.Manufacturers", "id");
            AddForeignKey("dbo.CPUs", "manufacturer_id", "dbo.Manufacturers", "id");
            AddForeignKey("dbo.CPU_Cooler", "manufacturer_id", "dbo.Manufacturers", "id");
            AddForeignKey("dbo.GPUs", "ram_type_id", "dbo.RAM_type", "id");
            AddForeignKey("dbo.GPUs", "GPU_technology_id", "dbo.GPU_technology", "id");
            AddForeignKey("dbo.GPUs", "GPU_frame_Sync_id", "dbo.GPU_frame_sync", "id");
            AddForeignKey("dbo.ROMs", "_interface_id", "dbo.Component_interface", "id");
            AddForeignKey("dbo.GPUs", "gpu_interface_id", "dbo.Component_interface", "id");
            AddForeignKey("dbo.ManufacturerGPUs", "GPU_id", "dbo.GPUs", "id", cascadeDelete: true);
            AddForeignKey("dbo.ManufacturerGPUs", "Manufacturer_id", "dbo.Manufacturers", "id", cascadeDelete: true);
        }
    }
}
